package app.numera.calculator.feature.converter

import app.numera.calculator.R
import app.numera.calculator.units.Dimension

/**
 * Maps a unit id onto its display name and symbol.
 *
 * Written as an exhaustive `when` over direct `R.string` constants rather than as a
 * name lookup through `resources.getIdentifier`. Release builds run with
 * `isShrinkResources = true`, and the shrinker cannot see a resource that is only
 * ever named by a runtime-built string — every unit name would be stripped, and the
 * failure would appear only in the release APK, only at runtime, and only when the
 * user opened the converter.
 */
object UnitNames {

    /**
     * Display name for [id].
     *
     * Every id in the catalogue has an arm below, so the fallback is only ever reached by a
     * unit added to [app.numera.calculator.units.UnitCatalog] and forgotten here. It has to
     * be an obvious placeholder: the fallback used to be `R.string.app_name`, which drew the
     * missing unit as "Numera" — a caption plausible enough to survive review and ship, on
     * the one screen whose entire job is naming quantities.
     */
    fun nameRes(id: String): Int = when (id) {
        "acre" -> R.string.unit_acre
        "angstrom" -> R.string.unit_angstrom
        "arcminute" -> R.string.unit_arcminute
        "arcsecond" -> R.string.unit_arcsecond
        "astronomical_unit" -> R.string.unit_astronomical_unit
        "atmosphere" -> R.string.unit_atmosphere
        "bar" -> R.string.unit_bar
        "barrel_oil" -> R.string.unit_barrel_oil
        "bit" -> R.string.unit_bit
        "bit_per_second" -> R.string.unit_bit_per_second
        "btu" -> R.string.unit_btu
        "btu_per_hour" -> R.string.unit_btu_per_hour
        "byte" -> R.string.unit_byte
        "byte_per_second" -> R.string.unit_byte_per_second
        "calorie" -> R.string.unit_calorie
        "calorie_per_second" -> R.string.unit_calorie_per_second
        "carat" -> R.string.unit_carat
        "celsius" -> R.string.unit_celsius
        "centimetre" -> R.string.unit_centimetre
        "century" -> R.string.unit_century
        "chain" -> R.string.unit_chain
        "cubic_centimetre" -> R.string.unit_cubic_centimetre
        "cubic_foot" -> R.string.unit_cubic_foot
        "cubic_inch" -> R.string.unit_cubic_inch
        "cubic_metre" -> R.string.unit_cubic_metre
        "cubic_yard" -> R.string.unit_cubic_yard
        "cup_us" -> R.string.unit_cup_us
        "day" -> R.string.unit_day
        "decade" -> R.string.unit_decade
        "decimetre" -> R.string.unit_decimetre
        "degree" -> R.string.unit_degree
        "dyne" -> R.string.unit_dyne
        "electronvolt" -> R.string.unit_electronvolt
        "fahrenheit" -> R.string.unit_fahrenheit
        "fathom" -> R.string.unit_fathom
        "fluid_ounce_imperial" -> R.string.unit_fluid_ounce_imperial
        "fluid_ounce_us" -> R.string.unit_fluid_ounce_us
        "foot" -> R.string.unit_foot
        "foot_per_second" -> R.string.unit_foot_per_second
        "foot_pound" -> R.string.unit_foot_pound
        "fortnight" -> R.string.unit_fortnight
        "furlong" -> R.string.unit_furlong
        "gallon_imperial" -> R.string.unit_gallon_imperial
        "gallon_us" -> R.string.unit_gallon_us
        "gibibit" -> R.string.unit_gibibit
        "gibibit_per_second" -> R.string.unit_gibibit_per_second
        "gibibyte" -> R.string.unit_gibibyte
        "gibibyte_per_second" -> R.string.unit_gibibyte_per_second
        "gigabit" -> R.string.unit_gigabit
        "gigabit_per_second" -> R.string.unit_gigabit_per_second
        "gigabyte" -> R.string.unit_gigabyte
        "gigabyte_per_second" -> R.string.unit_gigabyte_per_second
        "gigahertz" -> R.string.unit_gigahertz
        "gradian" -> R.string.unit_gradian
        "grain" -> R.string.unit_grain
        "gram" -> R.string.unit_gram
        "hectare" -> R.string.unit_hectare
        "hectopascal" -> R.string.unit_hectopascal
        "hertz" -> R.string.unit_hertz
        "horsepower_mechanical" -> R.string.unit_horsepower_mechanical
        "horsepower_metric" -> R.string.unit_horsepower_metric
        "hour" -> R.string.unit_hour
        "inch" -> R.string.unit_inch
        "inhg" -> R.string.unit_inhg
        "joule" -> R.string.unit_joule
        "kelvin" -> R.string.unit_kelvin
        "kibibit" -> R.string.unit_kibibit
        "kibibit_per_second" -> R.string.unit_kibibit_per_second
        "kibibyte" -> R.string.unit_kibibyte
        "kibibyte_per_second" -> R.string.unit_kibibyte_per_second
        "kilobit" -> R.string.unit_kilobit
        "kilobit_per_second" -> R.string.unit_kilobit_per_second
        "kilobyte" -> R.string.unit_kilobyte
        "kilobyte_per_second" -> R.string.unit_kilobyte_per_second
        "kilocalorie" -> R.string.unit_kilocalorie
        "kilogram" -> R.string.unit_kilogram
        "kilogram_force" -> R.string.unit_kilogram_force
        "kilohertz" -> R.string.unit_kilohertz
        "kilojoule" -> R.string.unit_kilojoule
        "kilometre" -> R.string.unit_kilometre
        "kilometre_per_hour" -> R.string.unit_kilometre_per_hour
        "kilometre_per_litre" -> R.string.unit_kilometre_per_litre
        "kilonewton" -> R.string.unit_kilonewton
        "kilopascal" -> R.string.unit_kilopascal
        "kilowatt" -> R.string.unit_kilowatt
        "kilowatt_hour" -> R.string.unit_kilowatt_hour
        "knot" -> R.string.unit_knot
        "league" -> R.string.unit_league
        "light_year" -> R.string.unit_light_year
        "litre" -> R.string.unit_litre
        "litre_per_100km" -> R.string.unit_litre_per_100km
        "mebibit" -> R.string.unit_mebibit
        "mebibit_per_second" -> R.string.unit_mebibit_per_second
        "mebibyte" -> R.string.unit_mebibyte
        "mebibyte_per_second" -> R.string.unit_mebibyte_per_second
        "megabit" -> R.string.unit_megabit
        "megabit_per_second" -> R.string.unit_megabit_per_second
        "megabyte" -> R.string.unit_megabyte
        "megabyte_per_second" -> R.string.unit_megabyte_per_second
        "megahertz" -> R.string.unit_megahertz
        "megapascal" -> R.string.unit_megapascal
        "megawatt" -> R.string.unit_megawatt
        "metre" -> R.string.unit_metre
        "metre_per_second" -> R.string.unit_metre_per_second
        "microgram" -> R.string.unit_microgram
        "micrometre" -> R.string.unit_micrometre
        "microsecond" -> R.string.unit_microsecond
        "mile" -> R.string.unit_mile
        "mile_per_hour" -> R.string.unit_mile_per_hour
        "millibar" -> R.string.unit_millibar
        "milligram" -> R.string.unit_milligram
        "millilitre" -> R.string.unit_millilitre
        "millimetre" -> R.string.unit_millimetre
        "milliradian" -> R.string.unit_milliradian
        "millisecond" -> R.string.unit_millisecond
        "minute" -> R.string.unit_minute
        "mmhg" -> R.string.unit_mmhg
        "month" -> R.string.unit_month
        "mpg_imperial" -> R.string.unit_mpg_imperial
        "mpg_us" -> R.string.unit_mpg_us
        "nanometre" -> R.string.unit_nanometre
        "nanosecond" -> R.string.unit_nanosecond
        "nautical_mile" -> R.string.unit_nautical_mile
        "newton" -> R.string.unit_newton
        "ounce" -> R.string.unit_ounce
        "parsec" -> R.string.unit_parsec
        "pascal" -> R.string.unit_pascal
        "pebibit" -> R.string.unit_pebibit
        "pebibit_per_second" -> R.string.unit_pebibit_per_second
        "pebibyte" -> R.string.unit_pebibyte
        "pebibyte_per_second" -> R.string.unit_pebibyte_per_second
        "petabit" -> R.string.unit_petabit
        "petabit_per_second" -> R.string.unit_petabit_per_second
        "petabyte" -> R.string.unit_petabyte
        "petabyte_per_second" -> R.string.unit_petabyte_per_second
        "pint_imperial" -> R.string.unit_pint_imperial
        "pint_us" -> R.string.unit_pint_us
        "pound" -> R.string.unit_pound
        "pound_force" -> R.string.unit_pound_force
        "poundal" -> R.string.unit_poundal
        "psi" -> R.string.unit_psi
        "quart_imperial" -> R.string.unit_quart_imperial
        "quart_us" -> R.string.unit_quart_us
        "radian" -> R.string.unit_radian
        "rankine" -> R.string.unit_rankine
        "reaumur" -> R.string.unit_reaumur
        "rpm" -> R.string.unit_rpm
        "second" -> R.string.unit_second
        "slug" -> R.string.unit_slug
        "square_centimetre" -> R.string.unit_square_centimetre
        "square_foot" -> R.string.unit_square_foot
        "square_inch" -> R.string.unit_square_inch
        "square_kilometre" -> R.string.unit_square_kilometre
        "square_metre" -> R.string.unit_square_metre
        "square_mile" -> R.string.unit_square_mile
        "square_millimetre" -> R.string.unit_square_millimetre
        "square_yard" -> R.string.unit_square_yard
        "stone" -> R.string.unit_stone
        "tablespoon_us" -> R.string.unit_tablespoon_us
        "teaspoon_us" -> R.string.unit_teaspoon_us
        "tebibit" -> R.string.unit_tebibit
        "tebibit_per_second" -> R.string.unit_tebibit_per_second
        "tebibyte" -> R.string.unit_tebibyte
        "tebibyte_per_second" -> R.string.unit_tebibyte_per_second
        "terabit" -> R.string.unit_terabit
        "terabit_per_second" -> R.string.unit_terabit_per_second
        "terabyte" -> R.string.unit_terabyte
        "terabyte_per_second" -> R.string.unit_terabyte_per_second
        "terahertz" -> R.string.unit_terahertz
        "therm" -> R.string.unit_therm
        "thou" -> R.string.unit_thou
        "ton_force" -> R.string.unit_ton_force
        "ton_imperial" -> R.string.unit_ton_imperial
        "ton_us" -> R.string.unit_ton_us
        "tonne" -> R.string.unit_tonne
        "torr" -> R.string.unit_torr
        "turn" -> R.string.unit_turn
        "watt" -> R.string.unit_watt
        "watt_hour" -> R.string.unit_watt_hour
        "week" -> R.string.unit_week
        "yard" -> R.string.unit_yard
        "year" -> R.string.unit_year
        else -> R.string.unit_unknown
    }

    /** Short symbol for [id], e.g. "km" or "°C"; falls back exactly as [nameRes] does. */
    fun symbolRes(id: String): Int = when (id) {
        "acre" -> R.string.sym_acre
        "angstrom" -> R.string.sym_angstrom
        "arcminute" -> R.string.sym_arcminute
        "arcsecond" -> R.string.sym_arcsecond
        "astronomical_unit" -> R.string.sym_astronomical_unit
        "atmosphere" -> R.string.sym_atmosphere
        "bar" -> R.string.sym_bar
        "barrel_oil" -> R.string.sym_barrel_oil
        "bit" -> R.string.sym_bit
        "bit_per_second" -> R.string.sym_bit_per_second
        "btu" -> R.string.sym_btu
        "btu_per_hour" -> R.string.sym_btu_per_hour
        "byte" -> R.string.sym_byte
        "byte_per_second" -> R.string.sym_byte_per_second
        "calorie" -> R.string.sym_calorie
        "calorie_per_second" -> R.string.sym_calorie_per_second
        "carat" -> R.string.sym_carat
        "celsius" -> R.string.sym_celsius
        "centimetre" -> R.string.sym_centimetre
        "century" -> R.string.sym_century
        "chain" -> R.string.sym_chain
        "cubic_centimetre" -> R.string.sym_cubic_centimetre
        "cubic_foot" -> R.string.sym_cubic_foot
        "cubic_inch" -> R.string.sym_cubic_inch
        "cubic_metre" -> R.string.sym_cubic_metre
        "cubic_yard" -> R.string.sym_cubic_yard
        "cup_us" -> R.string.sym_cup_us
        "day" -> R.string.sym_day
        "decade" -> R.string.sym_decade
        "decimetre" -> R.string.sym_decimetre
        "degree" -> R.string.sym_degree
        "dyne" -> R.string.sym_dyne
        "electronvolt" -> R.string.sym_electronvolt
        "fahrenheit" -> R.string.sym_fahrenheit
        "fathom" -> R.string.sym_fathom
        "fluid_ounce_imperial" -> R.string.sym_fluid_ounce_imperial
        "fluid_ounce_us" -> R.string.sym_fluid_ounce_us
        "foot" -> R.string.sym_foot
        "foot_per_second" -> R.string.sym_foot_per_second
        "foot_pound" -> R.string.sym_foot_pound
        "fortnight" -> R.string.sym_fortnight
        "furlong" -> R.string.sym_furlong
        "gallon_imperial" -> R.string.sym_gallon_imperial
        "gallon_us" -> R.string.sym_gallon_us
        "gibibit" -> R.string.sym_gibibit
        "gibibit_per_second" -> R.string.sym_gibibit_per_second
        "gibibyte" -> R.string.sym_gibibyte
        "gibibyte_per_second" -> R.string.sym_gibibyte_per_second
        "gigabit" -> R.string.sym_gigabit
        "gigabit_per_second" -> R.string.sym_gigabit_per_second
        "gigabyte" -> R.string.sym_gigabyte
        "gigabyte_per_second" -> R.string.sym_gigabyte_per_second
        "gigahertz" -> R.string.sym_gigahertz
        "gradian" -> R.string.sym_gradian
        "grain" -> R.string.sym_grain
        "gram" -> R.string.sym_gram
        "hectare" -> R.string.sym_hectare
        "hectopascal" -> R.string.sym_hectopascal
        "hertz" -> R.string.sym_hertz
        "horsepower_mechanical" -> R.string.sym_horsepower_mechanical
        "horsepower_metric" -> R.string.sym_horsepower_metric
        "hour" -> R.string.sym_hour
        "inch" -> R.string.sym_inch
        "inhg" -> R.string.sym_inhg
        "joule" -> R.string.sym_joule
        "kelvin" -> R.string.sym_kelvin
        "kibibit" -> R.string.sym_kibibit
        "kibibit_per_second" -> R.string.sym_kibibit_per_second
        "kibibyte" -> R.string.sym_kibibyte
        "kibibyte_per_second" -> R.string.sym_kibibyte_per_second
        "kilobit" -> R.string.sym_kilobit
        "kilobit_per_second" -> R.string.sym_kilobit_per_second
        "kilobyte" -> R.string.sym_kilobyte
        "kilobyte_per_second" -> R.string.sym_kilobyte_per_second
        "kilocalorie" -> R.string.sym_kilocalorie
        "kilogram" -> R.string.sym_kilogram
        "kilogram_force" -> R.string.sym_kilogram_force
        "kilohertz" -> R.string.sym_kilohertz
        "kilojoule" -> R.string.sym_kilojoule
        "kilometre" -> R.string.sym_kilometre
        "kilometre_per_hour" -> R.string.sym_kilometre_per_hour
        "kilometre_per_litre" -> R.string.sym_kilometre_per_litre
        "kilonewton" -> R.string.sym_kilonewton
        "kilopascal" -> R.string.sym_kilopascal
        "kilowatt" -> R.string.sym_kilowatt
        "kilowatt_hour" -> R.string.sym_kilowatt_hour
        "knot" -> R.string.sym_knot
        "league" -> R.string.sym_league
        "light_year" -> R.string.sym_light_year
        "litre" -> R.string.sym_litre
        "litre_per_100km" -> R.string.sym_litre_per_100km
        "mebibit" -> R.string.sym_mebibit
        "mebibit_per_second" -> R.string.sym_mebibit_per_second
        "mebibyte" -> R.string.sym_mebibyte
        "mebibyte_per_second" -> R.string.sym_mebibyte_per_second
        "megabit" -> R.string.sym_megabit
        "megabit_per_second" -> R.string.sym_megabit_per_second
        "megabyte" -> R.string.sym_megabyte
        "megabyte_per_second" -> R.string.sym_megabyte_per_second
        "megahertz" -> R.string.sym_megahertz
        "megapascal" -> R.string.sym_megapascal
        "megawatt" -> R.string.sym_megawatt
        "metre" -> R.string.sym_metre
        "metre_per_second" -> R.string.sym_metre_per_second
        "microgram" -> R.string.sym_microgram
        "micrometre" -> R.string.sym_micrometre
        "microsecond" -> R.string.sym_microsecond
        "mile" -> R.string.sym_mile
        "mile_per_hour" -> R.string.sym_mile_per_hour
        "millibar" -> R.string.sym_millibar
        "milligram" -> R.string.sym_milligram
        "millilitre" -> R.string.sym_millilitre
        "millimetre" -> R.string.sym_millimetre
        "milliradian" -> R.string.sym_milliradian
        "millisecond" -> R.string.sym_millisecond
        "minute" -> R.string.sym_minute
        "mmhg" -> R.string.sym_mmhg
        "month" -> R.string.sym_month
        "mpg_imperial" -> R.string.sym_mpg_imperial
        "mpg_us" -> R.string.sym_mpg_us
        "nanometre" -> R.string.sym_nanometre
        "nanosecond" -> R.string.sym_nanosecond
        "nautical_mile" -> R.string.sym_nautical_mile
        "newton" -> R.string.sym_newton
        "ounce" -> R.string.sym_ounce
        "parsec" -> R.string.sym_parsec
        "pascal" -> R.string.sym_pascal
        "pebibit" -> R.string.sym_pebibit
        "pebibit_per_second" -> R.string.sym_pebibit_per_second
        "pebibyte" -> R.string.sym_pebibyte
        "pebibyte_per_second" -> R.string.sym_pebibyte_per_second
        "petabit" -> R.string.sym_petabit
        "petabit_per_second" -> R.string.sym_petabit_per_second
        "petabyte" -> R.string.sym_petabyte
        "petabyte_per_second" -> R.string.sym_petabyte_per_second
        "pint_imperial" -> R.string.sym_pint_imperial
        "pint_us" -> R.string.sym_pint_us
        "pound" -> R.string.sym_pound
        "pound_force" -> R.string.sym_pound_force
        "poundal" -> R.string.sym_poundal
        "psi" -> R.string.sym_psi
        "quart_imperial" -> R.string.sym_quart_imperial
        "quart_us" -> R.string.sym_quart_us
        "radian" -> R.string.sym_radian
        "rankine" -> R.string.sym_rankine
        "reaumur" -> R.string.sym_reaumur
        "rpm" -> R.string.sym_rpm
        "second" -> R.string.sym_second
        "slug" -> R.string.sym_slug
        "square_centimetre" -> R.string.sym_square_centimetre
        "square_foot" -> R.string.sym_square_foot
        "square_inch" -> R.string.sym_square_inch
        "square_kilometre" -> R.string.sym_square_kilometre
        "square_metre" -> R.string.sym_square_metre
        "square_mile" -> R.string.sym_square_mile
        "square_millimetre" -> R.string.sym_square_millimetre
        "square_yard" -> R.string.sym_square_yard
        "stone" -> R.string.sym_stone
        "tablespoon_us" -> R.string.sym_tablespoon_us
        "teaspoon_us" -> R.string.sym_teaspoon_us
        "tebibit" -> R.string.sym_tebibit
        "tebibit_per_second" -> R.string.sym_tebibit_per_second
        "tebibyte" -> R.string.sym_tebibyte
        "tebibyte_per_second" -> R.string.sym_tebibyte_per_second
        "terabit" -> R.string.sym_terabit
        "terabit_per_second" -> R.string.sym_terabit_per_second
        "terabyte" -> R.string.sym_terabyte
        "terabyte_per_second" -> R.string.sym_terabyte_per_second
        "terahertz" -> R.string.sym_terahertz
        "therm" -> R.string.sym_therm
        "thou" -> R.string.sym_thou
        "ton_force" -> R.string.sym_ton_force
        "ton_imperial" -> R.string.sym_ton_imperial
        "ton_us" -> R.string.sym_ton_us
        "tonne" -> R.string.sym_tonne
        "torr" -> R.string.sym_torr
        "turn" -> R.string.sym_turn
        "watt" -> R.string.sym_watt
        "watt_hour" -> R.string.sym_watt_hour
        "week" -> R.string.sym_week
        "yard" -> R.string.sym_yard
        "year" -> R.string.sym_year
        else -> R.string.sym_unknown
    }

    /** Localised category label. */
    fun dimensionRes(dimension: Dimension): Int = when (dimension) {
        Dimension.LENGTH -> R.string.dim_length
        Dimension.MASS -> R.string.dim_mass
        Dimension.AREA -> R.string.dim_area
        Dimension.VOLUME -> R.string.dim_volume
        Dimension.SPEED -> R.string.dim_speed
        Dimension.TEMPERATURE -> R.string.dim_temperature
        Dimension.TIME -> R.string.dim_time
        Dimension.ANGLE -> R.string.dim_angle
        Dimension.ENERGY -> R.string.dim_energy
        Dimension.POWER -> R.string.dim_power
        Dimension.FORCE -> R.string.dim_force
        Dimension.PRESSURE -> R.string.dim_pressure
        Dimension.FREQUENCY -> R.string.dim_frequency
        Dimension.DIGITAL_STORAGE -> R.string.dim_digital_storage
        Dimension.DATA_RATE -> R.string.dim_data_rate
        Dimension.FUEL_ECONOMY -> R.string.dim_fuel_economy
    }
}
